name: app_setup_module
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  file_picker: ^5.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path: ^1.8.2
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  msix: ^3.7.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

msix_config:
  display_name: App Setup Module
  publisher_display_name: Expample Company
  identity_name: com.databytesoft.app-setup-module
  msix_version: 1.0.0.0
  # logo_path: C:\path\to\logo.png
  capabilities: internetClient, location, microphone, webcam
